### ISSUE TITLE
indexeddb not available error

### ISSUE THREAD

**Issue by orthodoc** [VirgilSecurity/e3kit-js#1]
This lib falls back on using keyknox library to manage keys locally and in local storage.

Local storage is thereby restricted to using indexeddb which is not uniformly supported in all browsers.

Can we configure it to use localforage which has fallback options to websql and local storage in case indexddb is not available? In any case, the private key is stored in an encrypted format!!

**Comment by xlwknx** [comment]
As that lib is in active development, for now we are targeting modern browsers with IndexedDb support. Thank you for your question, that will help to cover your use case in the future, when our core API will stabilize. For now you could try to shim IndexedDb with this polyfill: https://github.com/axemclion/IndexedDBShim

**Comment by orthodoc** [comment]
Thank you.
