### ISSUE TITLE
cannot npm install from github 

### ISSUE THREAD

**Issue by orthodoc** [VirgilSecurity/e3kit-js#3]
as dist folder is in .gitignore cannot do npm install from github

can you please release with the updated import statement now for use in the project?

thanks

**Comment by xlwknx** [comment]
@orthodoc  Why do you need instal from github?
Dist folder intentionally in .gitignore. You can install it from npm or through npm link locally

**Comment by orthodoc** [comment]
@xlwknx at that time, the release was at 0.1.0 and the master branch carried your changes. Now that you have released 0.1.1 the issue is no longer relevant. Thank you.
